### PR TITLE
Add work around for SIP restrictions on macOS

### LINKED ISSUE #40: Trouble with auth on macOS due to SIP
If I try to clone a private repo, it prompts to ask for a username. I'd like it to auth automatically, like my command line git. I think that works because I have
```
credential.helper=osxkeychain
```
in my `git config --global -l`.

I can do
```julia
using Git
run(`$(git()) config --global --add credential.helper osxkeychain`)
```
which does set the setting correctly as I check with
```julia
julia> run(`$(git()) config --global -l`)
core.excludesfile=/Users/eph/.gitignore
core.editor=nano
user.name=Eric Hanson
user.email=5846501+ericphanson@users.noreply.github.com
credential.helper=osxkeychain
Process(setenv(`/Users/eph/.julia/artifacts/55445321
```
but when I try to clone a private repo, I get
```julia
julia> run(`$(git()) clone private_repo`)
Cloning into 'private'...
dyld: Library not loaded: @rpath/libgettextlib-0.20.1.dylib
  Referenced from: /Users/eph/.julia/artifacts/554453215888cc66406fca3bc8a2285995626b67/libexec/git-core/git
  Reason: image not found
error: git credential-osxkeychain get died of signal 6
Username for 'https://github.com': 

```

Any ideas?

### PR DESCRIPTION
**Pull request by giordano**
This requires https://github.com/JuliaPackaging/Yggdrasil/pull/4987.  I verified that without that PR, the new test fails, but with the PR they're successful.

CC @ericphanson @GunnarFarneback @staticfloat @mortenpi.

Fix #40.

### CODE REVIEW

**Comment by ericphanson** [comment]
Awesome!!

**Comment by giordano** [comment]
@ericphanson @GunnarFarneback @mortenpi After https://github.com/JuliaPackaging/Yggdrasil/pull/4987 makes it to the registry (in ~20 minutes or so), can you please try out this PR on your macOS systems?  I successfully ran the test on macOS and Linux (of course on Linux it was working also before this PR, but good to test anyway).

**Comment by giordano** [comment]
At least tests are passing on all platforms on CI :slightly_smiling_face:

**Comment by giordano** [comment]
Codecov is a required CI job, but it's failing because code coverage is apparently broken on the `@static` line.....

**Comment by DilumAluthge** [comment]
I removed Codecov from required. Is there an open Julia issue to track the issue of `@static` not being having correct code coverage reported?

**Review by DilumAluthge — APPROVED** [review]

**Comment by mortenpi** [comment]
This is awesome, the Documenter macOS tests pass as well with this!

**Comment by GunnarFarneback** [comment]
Confirmed that pointing https://github.com/GunnarFarneback/LocalRegistry.jl/pull/38 to this branch passes all tests.

**Comment by giordano** [comment]
>  Is there an open Julia issue to track the issue of `@static` not being having correct code coverage reported?

I don't know, but I wonder if it's a problem with nested `@static`?  Because the outer one is detected correctly, and this one is definitely stepped over, otherwise the new test wouldn't work on macOS.

**Pull request merged**
